DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS policy_config;
DROP TABLE IF EXISTS content_reports;
DROP TABLE IF EXISTS approval_requests;
DROP TABLE IF EXISTS ai_jobs;
DROP TABLE IF EXISTS knowledge_relations;
DROP TABLE IF EXISTS claims;
ALTER TABLE IF EXISTS knowledge_nodes DROP CONSTRAINT IF EXISTS knowledge_nodes_current_revision_fk;
DROP TABLE IF EXISTS knowledge_revisions;
DROP TABLE IF EXISTS knowledge_nodes;
DROP TABLE IF EXISTS submission_votes;
ALTER TABLE IF EXISTS submissions DROP CONSTRAINT IF EXISTS submissions_current_revision_fk;
DROP TABLE IF EXISTS submission_revisions;
DROP TABLE IF EXISTS submissions;
DROP TABLE IF EXISTS hot_event_items;
DROP TABLE IF EXISTS hot_events;
DROP TABLE IF EXISTS realtime_items;
DROP TABLE IF EXISTS sources;
DROP TABLE IF EXISTS interest_topics;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS interests;
DROP TABLE IF EXISTS knowledge_domains;
DROP TABLE IF EXISTS app_users;
